navbar:
  blog_title: Giraffish的博客
  ground_glass:
    enable: true
index:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/IMG_2537.jpg
  banner_img_height: 100
  slogan:
    text: 欢迎来到Giraffish的个人博客
post:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/IMG_2542.jpg
  banner_img_height: 85
  default_index_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/A84CE283-6EDF-41A8-B75F-65F94D4C8DE9.jpeg
archive:
  banner_img: https://s1.imagehub.cc/images/2024/07/22/1ec8a0eb13116d580b25ebbd11b22e94.jpeg
  banner_img_height: 85
  subtitle: null
category:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/IMG_2538.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: https://hexo-blog-netlify.oss-cn-shenzhen.aliyuncs.com/IMG_2543.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/8548a93a70264f5c9a2945c6dd85a4ca.jpeg
  banner_img_height: 80
  subtitle: null
  avatar: https://s1.imagehub.cc/images/2023/10/01/IMG_2539.jpeg
  name: Giraffish
  intro: Giraffish的个人博客
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
